apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: api-gateway
  labels:
    app: Api-Gateway
    tier: Service
    version: '0.2'
  name: api-gateway
  namespace: services
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: '0.2'
      name: api-gateway
    spec:
      imagePullSecrets:
      - name: azure-registry
      serviceAccountName: read-user
      automountServiceAccountToken: false
      containers:
      - name: api-gateway
        image: openvaspclientdev.azurecr.io/swiss-chain:api-gateway-1.35
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 20
        resources:
          requests:
            memory: 128Mi
            cpu: 40m
          limits:
            memory: 256Mi
            cpu: 100m
        env:
        - name: BuildNumber
          value: '0.2'
        - name: SETTINGS_URL
          value: 'http://consul-ui.internal.svc.cluster.local/v1/kv/gateway/settings?raw'
        - name: SERILOG_SETTINGS_URL
          value: 'http://consul-ui.internal.svc.cluster.local/v1/kv/serilog/settings?raw'
        - name: ENV_INFO
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      nodeSelector:
        type: services