apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
    tier: Service
  name: api-gateway
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: api-gateway
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 51.105.173.11/32
