apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
    tier: Service
  name: api-gateway
  namespace: openvasp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: api-gateway
  sessionAffinity: None
  type: ClusterIP
