apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-api
    tier: Service
  name: frontend-api
  namespace: openvasp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: frontend-api
  sessionAffinity: None
  type: ClusterIP
