apiVersion: v1
kind: Service
metadata:
  labels:
    app: transactions
    tier: Service
  name: transactions
  namespace: openvasp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: transactions
  sessionAffinity: None
  type: ClusterIP