apiVersion: v1
kind: Service
metadata:
  labels:
    app: integration
    tier: Service
  name: integration
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: integration
  sessionAffinity: None
  type: ClusterIP