apiVersion: v1
kind: Service
metadata:
  labels:
    app: whisper
    tier: Service
  name: whisper
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: whisper
  sessionAffinity: None
  type: ClusterIP

