apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: statistics
  labels:
    app: statistics
    tier: Service
    version: '0.1'
  name: statistics
  namespace: services
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: statistics
  template:
    metadata:
      labels:
        app: statistics
        version: '0.1'
      name: statistics
    spec:
      imagePullSecrets:
      - name: azure-registry
      serviceAccountName: read-user
      automountServiceAccountToken: false
      containers:
      - name: statistics
        image: openvaspclientdev.azurecr.io/swiss-chain:statistics-1.26
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 20
        resources:
          requests:
            memory: 128Mi
            cpu: 40m
          limits:
            memory: 256Mi
            cpu: 100m
        env:
        - name: BuildNumber
          value: '0.1'
        - name: SETTINGS_URL
          value: 'http://consul-ui.internal.svc.cluster.local/v1/kv/statistics/settings?raw'
        - name: SERILOG_SETTINGS_URL
          value: 'http://consul-ui.internal.svc.cluster.local/v1/kv/serilog/settings?raw'
        - name: ENV_INFO
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      nodeSelector:
        type: services