apiVersion: v1
kind: Service
metadata:
  labels:
    app: statistics
    tier: Service
  name: statistics
  namespace: openvasp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: statistics
  sessionAffinity: None
  type: ClusterIP